package com.lihao.extracts.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme - warm literary tones
val WarmBackground = Color(0xFFF8F4EE)
val WarmSurface = Color(0xFFFFFBF5)
val WarmSurfaceVariant = Color(0xFFF0EAE0)
val WarmPrimary = Color(0xFF8B5A3E)
val WarmOnPrimary = Color(0xFFFFFFFF)
val WarmPrimaryContainer = Color(0xFFF5E6D8)
val WarmOnPrimaryContainer = Color(0xFF3D2010)
val WarmSecondary = Color(0xFF6B7F62)
val WarmOnSecondary = Color(0xFFFFFFFF)
val WarmSecondaryContainer = Color(0xFFD8ECD0)
val WarmOnSecondaryContainer = Color(0xFF1F2B18)
val WarmTertiary = Color(0xFF7D5260)
val WarmOnTertiary = Color(0xFFFFFFFF)
val WarmBackground2 = Color(0xFFFEFBF6)
val WarmSurface2 = Color(0xFFFFFDF9)
val WarmOnBackground = Color(0xFF2D2926)
val WarmOnSurface = Color(0xFF2D2926)
val WarmOnSurfaceVariant2 = Color(0xFF6B6560)
val WarmOutline = Color(0xD0C9BFA8)
val WarmError = Color(0xFFBA1A1A)

// Dark theme - warm dark tones
val DarkBackground = Color(0xFF1A1816)
val DarkSurface = Color(0xFF2D2926)
val DarkSurfaceVariant = Color(0xFF3D3833)
val DarkPrimary = Color(0xFFD4A98C)
val DarkOnPrimary = Color(0xFF3D2010)
val DarkPrimaryContainer = Color(0xFF5A3828)
val DarkOnPrimaryContainer = Color(0xFFF5E6D8)
val DarkSecondary = Color(0xFFA8BF9A)
val DarkOnSecondary = Color(0xFF1F2B18)
val DarkSecondaryContainer = Color(0xFF3A4D32)
val DarkOnSecondaryContainer = Color(0xFFD8ECD0)
val DarkTertiary = Color(0xFFEFB8C8)
val DarkOnTertiary = Color(0xFF4A2532)
val DarkBackground2 = Color(0xFF1A1816)
val DarkSurface2 = Color(0xFF2D2926)
val DarkOnBackground = Color(0xFFE8E2DA)
val DarkOnSurface = Color(0xFFE8E2DA)
val DarkOnSurfaceVariant2 = Color(0xFFB8B0A6)
val DarkOutline = Color(0xFF6B6560)
val DarkError = Color(0xFFFFB4AB)
